#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$REPO_ROOT"

log() { printf "[check-docs] %s\n" "$*"; }

if [[ ! -x scripts/tools/generate-docs.sh ]]; then
  log "generate-docs.sh not found or not executable" >&2
  exit 2
fi

# Capture pre-state hash of autogenerated block
PRE_HASH=$(grep -n "AUTOGEN:TOOLS_MATRIX:BEGIN" -n README.md || true)

bash scripts/tools/generate-docs.sh >/dev/null 2>&1 || { log "doc generation failed"; exit 1; }

if ! git diff --quiet README.md TOOLS_MATRIX.md; then
  log "Documentation drift detected. Run scripts/tools/generate-docs.sh and commit changes." >&2
  git --no-pager diff -- README.md TOOLS_MATRIX.md | sed 's/^/[diff] /'
  exit 3
fi

log "Docs consistent."
