name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  lint:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: |
          find scripts -type f -name '*.sh' -print0 | xargs -0 -n1 shellcheck -x || true
  pin-audit:
    name: Pin Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Pin Audit
        run: bash scripts/validation/verify-pins.sh
  smoke-minimal:
    name: Smoke Minimal (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show versions manifest
        run: cat manifests/versions.yaml
      - name: Placeholder smoke
        run: |
          echo "TODO: integrate minimal profile setup once profile system lands"
