name: Verify External Archives

on:
  push:
    paths:
      - 'manifests/versions.yaml'
      - 'scripts/security/verify-archives.sh'
  pull_request:
    paths:
      - 'manifests/versions.yaml'
      - 'scripts/security/verify-archives.sh'
  workflow_dispatch:
    inputs:
      full:
        description: 'Run full (download + hash) verification'
        required: false
        default: 'false'

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Quick size+hash header verify (no downloads)
        if: ${{ github.event_name != 'workflow_dispatch' || inputs.full == 'false' }}
        run: |
          bash scripts/security/verify-archives.sh --quick --filter eclipse
      - name: Full verification (download + hash)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.full == 'true' }}
        run: |
          bash scripts/security/verify-archives.sh --filter eclipse
